POST http://localhost:8080/user/update
X-ACCESS-TOKEN: cb1cb9b8-c7ae-47e1-8631-9db33c6869ea
Content-Type: application/json

{
	"firstName" : "Alex",
	"email" : "AKirus@inbox.ru",
	"lastName" : "Turchynovich",
	"pasword" : "test"
}

###

POST http://localhost:8080/user/update/4
X-ACCESS-TOKEN: 68c6820a-f6fd-4516-bf63-06a43f5c3d51
Content-Type: application/json

{
	"firstName" : "Aliaksei"
}

###
update/{userId}